tasks:
  - name: Update OS
  - init: |
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt autoremove -y
      gp sync-done apt
      
  - name: Update NPM and Initialize Frontend
  - init: |
      npm update -g 
      npm install -g npm@latest
      gp sync-done npm
  
  - name: Install aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  
  - name: Initialize Backend
    init: |
      cd /workspace/aws-bootcamp-cruddur-2023/backend-flask
      pip3 install -r requirements.txt
  
  - name: postgres
    init: |
      gp sync-await apt
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt install -y postgresql-client-13 libpq-dev
      

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - ms-azuretools.vscode-docker
