tasks:
  - name: Update OS and NPM
  - init: |
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt autoremove -y
      npm update -g 
      npm install -g npm@latest
      gp sync-done apt-npm
  
  - name: Install aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  
  - name: Initialize Backend and Frontend
    init: |
      gp sync-await apt-npm
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i
      cd $THEIA_WORKSPACE_ROOT
  
  - name: postgres
    init: |
      gp sync-await apt-npm
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update -y
      sudo apt install -y postgresql-client-13 libpq-dev
    
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - ms-azuretools.vscode-docker
    - ms-python.python

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public

  command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source $THEIA_WORKSPACE_ROOT/backend-flask/bin/rds-update-sg-rule-gitpod